### ISSUE TITLE
technical details

### ISSUE THREAD

**Issue by bsr203** [vslinko/ripster#13]
Hello,

I have few doubts on how you organize and use graphql schema along with acl. I may give a shot at writing a wiki page once I am clear about this. Most of the doubts are because I am too new to graphql and relay.
1. `schema/rootQuery.js`

so, there is ONE root field, `viewer` and all the fields defined in `rootQueryFields` are mapped into relation/connection through `attachFields` ? Is this necessary or can we have multiple root query nodes?
1. For acl to work, does all the query need to be in `viewer` ?
2. can you talk a bit about acl like
   3.1) can we have authorization per field ( I saw the wrapper is on each field, so I guess the answer is yes)
   3.2) How performant is doing this per field.
   3.3) How it is handled for relations. Is it possible to restrict per field on the edges?

I have more but may help me to proceed with your explanation.

thanks a ton again,
bsr.

**Comment by vslinko** [comment]
Hello,
1. `viewer` field is required for Relay, because Relay now can't make custom queries to root fields.
2. ACL isn't related to `viewer`. You need to use `wrapField` to make ACL work.
3. answers:
   1. Yes, you're right :smile: But only per relation field.
   2. It depends. It performant while your ACL is synchronous and makes no queries to database. If your ACL is database-dependent so it will make additional database query per each field.
   3. You could use `wrapConnectionField` to filter edges by ACL.

Right now ACL is working on object level but not on object field level. It means you can't filter specific regular fields (like strings) from response, only relation fields.

**Comment by bsr203** [comment]
I do not see an explicit reference of `viewer` in relay source though (only in tests). Also, `graphql-relay-js` supports multiple fields. I have added a [gitter](https://gitter.im/bsr203/ripster#) room here and it will tremendously help if you can spare some time. Please ping me when you are available.  thanks.

https://github.com/graphql/graphql-relay-js/blob/master/src/__tests__/starWarsSchema.js

```
/**
 * This is the type that will be the root of our query, and the
 * entry point into our schema.
 *
 * This implements the following type system shorthand:
 *   type Query {
 *     rebels: Faction
 *     empire: Faction
 *     node(id: String!): Node
 *   }
 */
var queryType = new GraphQLObjectType({
  name: 'Query',
  fields: () => ({
    rebels: {
      type: factionType,
      resolve: () => getRebels(),
    },
    empire: {
      type: factionType,
      resolve: () => getEmpire(),
    },
    node: nodeField
  })
});
```

**Comment by vslinko** [comment]
Relay supports root fields, but that fields have limits. Read more [here](https://github.com/facebook/relay/issues/112).

**Comment by bsr203** [comment]
thank you.
