### ISSUE TITLE
Any plan to support postgres(sql) & relay & react-router?

### ISSUE THREAD

**Issue by filod** [vslinko/ripster#3]
GREAT GREAT WORK i've seen for now.

AAA are really useful for me, i'm wondering if it is possible(or plan) to support:

1) AAA based on postgres(sql)
2) relay (heard that relay could coexist with flux, also noticed your version of relay)
3) react-router 1.0 (is vstack-router better ?)

for future version of ripster? 

many many thanks!

hope ripster  to become a real powerful framework for modern web develpment even native app develpment!

**Comment by vslinko** [comment]
Hello!

Thank you for your feedback and sorry for long delay. I was on vacation all this time.

First of all I should tell that Ripster is totalitarian framework. It means that Ripster provides only one solution for every problem. I won't support all databases, all routers, all validators, etc. Also it means that Ripster includes only those solutions that I like.

I'll try to answer your questions:
1. I don't think I will support PostgreSQL because I don't use it. But you could change any part of Ripster in your fork. You can ask me any question about Rispter internals.
2. Yes, I will support Relay with Redux. Stay tuned.
3. Right now `vstack-router` is better for me, but I'll think about migration to RR1.0 after Relay support.

**Comment by filod** [comment]
Thank you for reply. Really exciting about the future work. again thanks for the great work.
