### ISSUE TITLE
Integrate components style guilde generator

### ISSUE THREAD

**Issue by bsr203** [vslinko/ripster#36]
explore https://github.com/sapegin/react-styleguidist
https://github.com/sourcejs/sourcejs-react-styleguidist
http://sourcejs.com/

Hi, please disregard if you think we are adding too many deps. but, I kinda like living documentation / styleguides and an easy way to prototype components. The linked library looks less invasive, but it is not mature. They are adding indexing and better navs. you may know better options. Please share your opinion.

**Comment by vslinko** [comment]
Hi. We're tried to integrate https://github.com/rpominov/react-demo for work on components separately from the whole app, but we're refused this workflow because it isn't suitable for us.
May be we will try again later.

Anyway, thank you for the link to `react-styleguidist`, it's a very good solution.
You can make PR with `react-styleguidist` integration if you want to see it in `ripster` and if you can support this part in the future.

**Comment by bsr203** [comment]
Looks like now everything is dumped to one page. https://github.com/sapegin/react-styleguidist/issues/28 
I will try it out and integrate if found compelling. Thank you for link to `react-demo`.
